services:
  - type: web
    name: technology_learner
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn technology_learner.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
